### ISSUE TITLE
Mobile 中国的手机号码,虚拟运营商的号码支持吗？

### ISSUE THREAD

**Issue by OVERSKY2003** [yoojia/FireEye#7]
Mobile 中国的手机号码,虚拟运营商的号码支持吗？具体的验证规则是什么？
如果有新的号码段出来，FireEye是本地验证，到时验证不通过怎么办？

**Comment by yoojia** [comment]
抱歉啊，现在才注意这项目的Issue。虽然晚了点，但也应当回复下。中国手机号的号码规则，一开始我是非常严格的格式来校验，但存在你所描述的问题，有新号段出来会导致校验不通过。这种情况下可以通过自定义校验规则来解决。在新的项目NextInputs-Android中，我把它的验证规则改成简单的了，校验手机号的位数及首位数字为1
