### ISSUE TITLE
Demo中如果edittext比较多，上下滚动会出现自动回滚的问题

### ISSUE THREAD

**Issue by Jacky-Chen-Pro** [yoojia/FireEye#8]
和标题描述差不多，这个我考虑了一下，可能是因为你刻意这么做的，但是还是觉得有点奇怪

**Comment by yoojia** [comment]
咦，我才看到你的issue啊。这个不是我刻意的。是ScrollView对Error的处理。可以的话，建议你使用NextInputs-Android项目。FireEye因为只能用于Android，不能用于JavaSE项目的原因，暂时不再维护了。
